Mailchimp signup
harvard-lil/capstone pull request #1141
Opened 2019-08-23 19:07 UTC by ChefAndy

Killed our internal mailing list sign-up functionality and pointed our mailing list sign-up form right at our mailchimp campaign.

2019-08-26 19:04 UTC, jcushman requested changes
Thanks! Just a couple of tweaks.

2019-08-26 19:04 UTC, jcushman commented on capstone/capapi/migrations/0016_delete_mailinglist.py
> +class Migration(migrations.Migration):
Let's wait to delete the model until the rest of this lands, so we don't have to be too precise about the timing of copying the data over.

2019-08-26 19:04 UTC, jcushman commented on capstone/capweb/templates/index.html
> +          <form action="https://law.us3.list-manage.com/subscribe/post?u=4290964398813d739f2398db0&amp;id=e097736c6f"
Can we make the magic numbers here (and same elsewhere) into settings? That way dev/staging sites won't post to the real mailing list.

2019-08-27 16:52 UTC, ChefAndy commented on capstone/capweb/templates/index.html
> +          <form action="https://law.us3.list-manage.com/subscribe/post?u=4290964398813d739f2398db0&amp;id=e097736c6f"
Sure.

2019-08-27 16:53 UTC, ChefAndy commented on capstone/capapi/migrations/0016_delete_mailinglist.py
> +class Migration(migrations.Migration):
Ok.

2019-08-28 14:36 UTC, merged

2019-08-28 14:36 UTC, jcushman commented
Thanks!