Add range request middleware
harvard-lil/capstone pull request #739
Opened 2018-12-17 21:24 UTC by bensteinberg

2018-12-17 21:30 UTC, bensteinberg commented
Addresses #730 -- note that there are no tests for this yet.

2018-12-18 16:35 UTC, bensteinberg commented
WIP, do not merge. TODO:
- use regexes
- handle or ignore IF_RANGE
- confirm that `os.fstat` is the right way to get at the size
- clamp start and end correctly
- add tests

2018-12-18 21:34 UTC, bensteinberg commented
Also TODO, per @jcushman :
- add `Accept-Ranges: bytes` to 200 responses for files

2019-02-05 16:09 UTC, jcushman requested changes

2019-02-05 16:09 UTC, jcushman commented on capstone/capapi/middleware.py
> +        units = "bytes="
For this block, we can re-use some existing code from Werkzeug:

```
>>> from werkzeug.http import parse_range_header
>>> ranges = parse_range_header('bytes=1-2')
>>> ranges.ranges
[(1, 3)]
>>> ranges.units
'bytes'
```

Note this behaves a little differently in that it returns None for malformed headers -- probably fine in practice.

2019-02-05 16:09 UTC, jcushman commented on capstone/capapi/middleware.py
> +            def fchunks(start, end):
This should use `seek` and much larger chunk sizes for efficiency. Something along the lines of:

```
def fchunks(start, end):
    remaining = end - start
    f.seek(start)
    while remaining > 0:
        chunk = f.read(min(remaining, 2**20))
        if not chunk:
            break
        yield chunk
        remaining -= len(chunk)
```

Though that may have an off-by-one error -- not sure I used start and end correctly.

2019-02-06 17:46 UTC, jcushman approved these changes

2019-02-06 17:47 UTC, merged