Styled XML— Model change and test, fab task
harvard-lil/capstone pull request #834
Opened 2019-03-15 20:39 UTC by ChefAndy

Changed the CaseXML model to include a field for styled XML, and a method to update it.
Also added a test for that stuff.
Added a few arguments to the generate styled XML function to specify skipping dups
without raising an exception, and also appended a comment to the generated XML which
says if the text didn't totally match up with the ALTO.
Added a fab task which loops through each volume, synchronously, and asyncrhonously
updates the styled text for all of the cases in that volume.

2019-03-18 17:03 UTC, jcushman requested changes
A couple of suggestions on the storage and processing side ...

2019-03-18 17:03 UTC, jcushman commented on capstone/capdb/models.py
> +    styled_case_body = XMLField(blank=True, null=True)
Let's do this as a separate table, like `CaseText` (which is another cache of case output). There's a bunch of stuff that might assume that fetches from `CaseXML` are fast if they don't include `orig_xml`.

2019-03-18 17:03 UTC, jcushman commented on capstone/fabfile.py
> +    @shared_task
I don't think this task will get discovered by celery when it's defined here.

2019-03-18 17:03 UTC, jcushman commented on capstone/fabfile.py
> +        job_list = group([ update_styled_xml.s(case_xml) for case_xml
This doesn't really work with celery. Whatever input you queue for a job has to be serialized, stored in redis, and then pulled off and deserialized by the workers. So the job parameters should be json-serializable and small, like IDs, rather than Django ORM objects. It's also a little hairy to queue millions of jobs and wait for the result -- should work in theory, but may not in practice.

Check out `create_case_metadata_from_all_vols` and `create_case_metadata_from_vol` in tasks.py for a good example of how to handle this. Going per-volume breaks the job into 40,000, which is more manageable, and allows us to fetch data efficiently from the ORM for each volume. If you need to gather errors, it's probably a good idea to write them to the log from celery (I think just print), or write them to a table -- it's not reliable to assume the original task will still be running when all the subtasks are complete.

To get a feel for this stuff it might be worth getting celery running locally -- I think Ben said the Docker setup is currently working for him.

2019-03-19 15:24 UTC, ChefAndy commented on capstone/capdb/models.py
> +    styled_case_body = XMLField(blank=True, null=True)
ok, makes sense

2019-03-19 15:27 UTC, ChefAndy commented on capstone/fabfile.py
> +        job_list = group([ update_styled_xml.s(case_xml) for case_xml
ah, I see. I'll see if I can fix my horked docker setup and work in a more representative environment.

2019-03-25 14:57 UTC, merged