Cite
harvard-lil/capstone pull request #972
Opened 2019-05-17 02:35 UTC by anastasia

- added checking if google bot functionality
- if it is, sending request through and showing full case text, along with schema specifying this content isn't free
- added checks for google bot in permissions, and cite/views

2019-05-20 18:42 UTC, merged

2019-05-20 19:07 UTC, jcushman requested changes
Good progress! Some tweaks to make ...

2019-05-20 19:07 UTC, jcushman commented on capstone/capweb/helpers.py
> +    if not user_agent.is_bot:
This seems simpler to do without the 3rd party library as `if "Googlebot" in request.META.get('HTTP_USER_AGENT', ''):`. That will also avoid running this check for non-Google bots.

2019-05-20 19:07 UTC, jcushman commented on capstone/capweb/helpers.py
> +    ip, _ = get_client_ip(request)
We want to specifically get the IP address from `request.user.ip_address`. This makes sure that we're getting the correct IP address, via proxies, and also that the response will not be cached. Unfortunately setting up the request.user object will complicate one of your tests a bit.

(IP address checking is tricky in general, because requests arrive to Django via multiple proxy servers, so there's no one standard place that the true user IP lives, and if you check the wrong place you can actually let an attacker control the answer. It's best to check in with Ben about how the system is set up. On CAP it ends up in the HTTP_X_FORWARDED_FOR header at the moment.)

(Caching is also tricky -- our middleware marks pages as not-cachable-by-cloudflare if user attributes have been accessed, so getting ip_address from there should make sure the caching behavior is correct. I *think* the current code won't cache google requests anyway, just because request.session is checked first, but good to not make that depend on something unrelated to the googlebot check itself.)

2019-05-20 19:07 UTC, jcushman commented on capstone/capweb/helpers.py
> +def get_schema(response):
This seems pretty specific to your test logic -- maybe it wants to live in test_views.py?

2019-05-20 19:07 UTC, jcushman commented on capstone/capapi/permissions.py
> +    elif helpers.is_google_bot(request):
We don't want to add this test here -- that will also open up API queries. Instead we want to use `serializers.NoLoginCaseSerializer` down in cite/views.py.

2019-05-20 19:07 UTC, jcushman commented on capstone/cite/tests/test_views.py
> +    response = client.get(url, follow=True)
Let's add an `assert not is_cached(response)` in here to make sure the response isn't getting cached.

2019-05-22 00:19 UTC, anastasia commented on capstone/capweb/helpers.py
> +    ip, _ = get_client_ip(request)
Ah, I see! I also see the wrap_user function now. Fixing